config/routes.rb
Lucidly::Application.routes.draw do
  devise_for :users

  resources :admin, :only => [:index] do
    member do
      get 'editreject'
      put 'reject'
      put 'accept'
    end
    collection do
      get 'dreams'
    end
  end

  resources :dreams do
    collection do
      get 'about'
      get 'all'
      get 'mydreams'
    end
    member do
      put 'submit'
    end
    member { post :vote }
    resources :comments, :only => [:create, :destroy]
  end

  get 'tags/:tag', to: 'dreams#index', as: :tag
  root :to => "dreams#index"

end

app/models/dream.rb
class Dream < ActiveRecord::Base
  attr_accessible :title, :teaser, :body, :version, :changelog, :user_id, :message, :freezebody, :state, :submitted, :accepted, :tag_list
  belongs_to :user
  has_many :comments, :dependent => :destroy

  acts_as_taggable
  has_reputation :votes, source: :user, aggregated_by: :sum

  validates :user_id, :presence => true
  validates :title, :presence => true, :length => { :maximum => 80 }
  validates :teaser, :presence => true, :length => { :maximum => 500 }
  validates :body, :presence => true
  validates :version, :length => { :maximum => 120 }
  validates :changelog, :length => { :maximum => 2000 }
  validates :message, :length => { :maximum => 5000 }
  validates :state, :presence => true, :numericality => true, :inclusion => { :in => 0..4 }

  scope :featured, where(state: '4')
  scope :standard, where(state: '3')
  scope :rejected, where(state: '2')
  scope :submitted, where(state: '1')
  scope :pvt, where(state: '0')
  scope :published, where("state = '3' or state = '4'")
  scope :recent, where("created_at >= to_timestamp(?)", Time.now-30.days.ago).order("created_at desc").first(5)
  scope :loved, find_with_reputation(:votes, :all, {:conditions => ["value >= ?", 1], :order => "votes DESC"}).first(5)

  def self.states
    { featured: Dream.featured.count,
      standard: Dream.standard.count,
      rejected: Dream.rejected.count,
      submitted: Dream.submitted.count,
      pvt: Dream.pvt.count,
      published: Dream.published.count
    }
  end

  def self.search(query)
    if query.present?
      where("title @@ :q or teaser @@ :q or body @@ :q", q: query)
    else
      scoped
    end
  end

  protected
    def record_not_found
      flash[:error] = 'The dream you requested could not be found.'
      redirect_to root_url
    end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :all, :show, :about]
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  # GET /dreams
  # GET /dreams.json
  def index
    @dreams = Dream.featured.paginate(:page => params[:page], :per_page => 8)
    @recent_dreams = Dream.recent
    @loved_dreams = Dream.loved

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dreams }
    end
  end

  def all
    @dreams = Dream.published.search(params[:query]).order('accepted desc').paginate(:page => params[:page], :per_page => 8)
    @recent_dreams = Dream.recent
    @loved_dreams = Dream.loved

    respond_to do |format|
      format.html { render 'index' }
      format.json  { render :json => @dreams }
    end

    if params[:tag]
      @dreams = Dream.tagged_with(params[:tag])
    else
      @dreams = Dream.all
    end
  end

  def mydreams
    @mydreams = current_user.dreams.all.paginate(:page => params[:page], :per_page => 5)
    @mydreams_total = current_user.dreams.all.count

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mydreams }
    end
  end

  # GET /dreams/1
  # GET /dreams/1.json
  def show
    @dream = Dream.find(params[:id])
    @comments = @dream.comments.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dream }
    end
  end

  # GET /dreams/new
  # GET /dreams/new.json
  def new
    @dream = current_user.dreams.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dream }
    end
  end

  # GET /dreams/1/edit
  def edit
    @dream = current_user.dreams.find(params[:id])
  end

  # POST /dreams
  # POST /dreams.json
  def create
    @dream = current_user.dreams.new(params[:dream])

    respond_to do |format|
      if @dream.save
        format.html { redirect_to @dream, notice: 'Dream was successfully created.' }
        format.json { render json: @dream, status: :created, location: @dream }
      else
        format.html { render action: "new" }
        format.json { render json: @dream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dreams/1
  # PUT /dreams/1.json
  def update
    @dream = current_user.dreams.find(params[:id])

    if @dream.state > 2
      params[:dream].delete(:title)
      params[:dream].delete(:teaser)
    end

    respond_to do |format|
      if @dream.update_attributes(params[:dream])
        format.html { redirect_to(@dream, :notice => 'Dream was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @dream.errors, :status => :unprocessable_entity }
      end
    end
  end

  def submit
    @dream = current_user.dreams.find(params[:id])

    if (@dream.state == 0) or (@dream.state == 2)
      @dream.state = 1
      @dream.submitted = Time.now

      if @dream.save
        flash[:notice] = 'Your dream was successfully submitted for approval.'
      else
        flash[:error] = 'There was an error while submitting your dream.'
      end
    else
      flash[:error] = 'This dream can not be submitted.'
    end

    respond_to do |format|
      format.html { redirect_to(:action => 'mydreams') }
      format.json  { head :ok }
    end
  end

  # DELETE /dreams/1
  # DELETE /dreams/1.json
  def destroy
   @dream = current_user.dreams.find(params[:id])

   if (@dream.state < 3)
     @dream.destroy
   else
    flash[:error] = 'The dream could not be deleted.'
   end

    respond_to do |format|
      format.html { redirect_to dreams_url }
      format.json { head :ok }
    end
  end

  def vote
    value = params[:type] == "up" ? 1 : -1
    @dream = Dream.find(params[:id])
    @dream.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, notice: "Thank you for voting!"
  end

  protected
    def record_not_found
      flash[:error] = 'The dream you requested could not be found.'
      redirect_to root_url
    end
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/views/dreams/_form.haml
= simple_form_for(@dream) do |f|
  - if @dream.errors.any?
    #error_explanation
      %ul
        - @dream.errors.full_messages.each do |msg|
          %li= msg
  - if @dream.state < 3
    = f.input :title, :label => 'Title'
    = f.input :teaser, :label => 'Teaser - dream summary'
  - else
    = f.input :title, :label => 'Title'
    = f.input :teaser, :label => 'Teaser - dream summary'
  = f.input :body, :label => 'Body - dream details'
  = f.input :tag_list, :label => 'Tags - seperate using comma'
  %div
    = f.submit "Save", class: "btn"
    = link_to 'View this dream', @dream
    = link_to 'Return to my dreams', mydreams_dreams_path

app/views/dreams/_sidebar.haml
.widget
  %h3
    %span Search
  .form-search
    = form_tag all_dreams_path, method: :get do
      = text_field_tag :query, params[:query]
      = submit_tag "Search", name: nil, class: "btn"
.widget
  %h3
    %span Recent
  %ul
    - @recent_dreams.each do |dream|
      - if dream.state == 3 || dream.state == 4
        %li= link_to dream.title, dream_path(dream)
.widget
  %h3
    %span Loved
  %ul
    - @loved_dreams.each do |dream|
      - if dream.state == 3 || dream.state == 4
        %li= link_to dream.title, dream_path(dream)
.widget
  %h3
    %span Tags
  %ul
    #tag_cloud
      - tag_cloud Dream.tag_counts, %w{s m l} do |tag, css_class|
        = link_to tag.name, tag_path(tag.name), class: css_class

app/views/dreams/about.haml
.span12
  %h3
    %span about
  .entry
    .matter
      %h5 A dream journal.
      %p
        Lucidly is a place to record your dreams, lucid or otherwise. You can share your dreams for publication on the front page or choose to keep them private for your records. Lucidly is completely free to use and all content is published under a non-commercial license. You can contribute code here:
        = succeed "." do
          %a{:href => "https://github.com/cpursley/Lucidly"} Lucidly

app/views/dreams/edit.html.haml
.span12
  .comments.well
    %h1 Editing dream
    = render 'form'
    = link_to 'Show', @dream
    |
    \#{link_to 'Back', dreams_path}

app/views/dreams/index.haml
.span12
  %h3
    %span
      = @dreams.count
      dreams
.span8
  .posts
    - @dreams.each do |dream|
      .matter
        %h2= link_to dream.title, dream
        .meta
          %i.icon-calendar
          = dream.created_at.strftime("%B %d, %Y")
          \-
          %i.icon-comment
          = dream.comments.count
          \-
          %i.icon-heart
          = dream.reputation_for(:votes).to_i
          \-
          %i.icon-tags
          = raw dream.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')
        %p= dream.teaser
    = will_paginate @dreams
.span4
  .sidebar
    = render 'sidebar'

app/views/dreams/mydreams.haml
.span12
  %h3
    %span
      Manage your (#{@mydreams_total}) dreams
  %br/
  %p= link_to 'Record new dream', new_dream_path, class: "btn"
  .entry
    - @mydreams.each do |dream|
      .matter
        %h2= link_to dream.title, dream
        .meta
          %i.icon-calendar
          Created: #{dream.created_at.strftime("%B %d, %Y")} / Updated: #{dream.updated_at.strftime("%B %d, %Y")}
        - if dream.state == 0
          .meta
            %i.icon-eye-close
            Current status: Private
        - if dream.state == 1
          .meta
            %i.icon-refresh
            Current status: Submitted on #{dream.submitted.strftime("%B %d, %Y")}
        - if dream.state == 2
          .meta
            %i.icon-flag
            Current status: Rejected on #{dream.submitted.strftime("%B %d, %Y")}
          .meta
            %i.icon-wrench
            Please read the comment, review your dream and submit it again!
          .meta
            %i.icon-envelope
            = dream.message
        - if dream.state == 3
          .meta
            %i.icon-thumbs-up
            Current status: Accepted and published as a standard dream on#{dream.accepted.strftime("%B %d, %Y")}
        - if dream.state == 4
          .meta
            %i.icon-thumbs-up
            Current status: Accepted and published as a
            %b featured dream
            on #{dream.accepted.strftime("%B %d, %Y")}
        %div
          %span= link_to 'Edit dream', edit_dream_path(dream), class: "btn btn-info"
          - if (dream.state == 0) or (dream.state == 2)
            %span= link_to "Submit now", submit_dream_path(dream), :method => :put, class: "btn btn-success"
          - if dream.state < 3
            %span= link_to 'Delete', dream, :confirm => 'Are you sure?', :method => :delete, class: "btn btn-danger"
        %br
  = will_paginate @mydreams

app/views/dreams/new.html.haml
.span12
  .comments.well
    %h3
      %span.comment-heading New Dream
    = render 'form'

app/views/dreams/show.haml
.span12
  %h3
    %span= @dream.title
  .entry
    .matter
      .meta
        %i.icon-calendar
        = @dream.created_at.strftime("%B %d, %Y")
        \-
        %i.icon-comment
        = @dream.comments.count
        \-
        %i.icon-heart
        = @dream.reputation_for(:votes).to_i
        %i.icon-tags
        = raw @dream.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')
      .comment-author
        %strong
          By #{@dream.user.fullname}
      %br
        %p= @dream.body
      .meta
        %i.icon-heart
        = pluralize @dream.reputation_for(:votes).to_i, "vote"
        | #{link_to "up", vote_dream_path(@dream, type: "up"), method: "post"}
  .comments.well
    %h3
      %span.comment-heading
        Comments - #{@dream.comments.count}
    - @comments.each do |comment|
      .media-list
        #li-comment-6.comment.byuser.comment-author-admin.bypostauthor.even.thread-even.depth-1
          #comment-6.comment-box
            .comment-author
              %strong= comment.user.fullname
            .cmeta
              = time_ago_in_words(comment.created_at)
              ago
            .clearfix
            %p= comment.body
      - if user_signed_in? and comment.user_id == current_user.id
        %span= link_to 'delete', dream_comment_path(@dream, comment), :confirm => 'Are you sure?', :method => :delete, :class => ""
  %br
    .comments.well
      %h3
        %span.comment-heading leave a comment
      - if user_signed_in?
        - if current_user.fullname == nil or current_user.fullname == ''
          .comment-author
            %strong
              Please complete your #{link_to "profile", edit_user_registration_path} before posting comments.
        - else
          .comment-author
            %strong= current_user.fullname
          %br
            = simple_form_for [@dream, current_user.comments.new] do |f|
              = f.text_area :body
              %div= f.submit "Add Comment", class: "btn"
      - else
        .signin
          Please #{link_to "sign in", new_user_session_path} before posting a comment.