config/routes.rb
Lucidly::Application.routes.draw do
  devise_for :users

  resources :admin, :only => [:index] do
    member do
      get 'editreject'
      put 'reject'
      put 'accept'
    end
    collection do
      get 'dreams'
    end
  end

  resources :dreams do
    collection do
      get 'about'
      get 'all'
      get 'mydreams'
    end
    member do
      put 'submit'
    end
    member { post :vote }
    resources :comments, :only => [:create, :destroy]
  end

  get 'tags/:tag', to: 'dreams#index', as: :tag
  root :to => "dreams#index"

end

app/views/admin/dreams.haml
.span12
  %h3
    %span
      Admin: #{@state_name.capitalize} Dreams
  - @dreams.each do |dream|
    %p
      %h4= link_to dream.title, dream
      Author: #{dream.user.fullname}
      \#{link_to 'Delete', dream, :confirm => 'This is admin delete despite of the dreams state. Are you sure?', :method => :delete}
      - if dream.state == 1
        = link_to 'Reject', editreject_admin_path(dream)
        = link_to 'Publish standard', accept_admin_path(dream, :value => '0'), :method => :put
        = link_to 'Publish featured', accept_admin_path(dream, :value => '1'), :method => :put
  = will_paginate @dreams

app/views/admin/editreject.haml
.span12
  .comments.well
    %section#admin
      %h4= link_to @dream.title, @dream
      Author: #{@dream.user.fullname}
      %br/
      = @dream.teaser
      %br/
      %br/
      %br/
      = form_for(@dream, :url => reject_admin_path(@dream)) do |f|
        - if @dream.errors.any?
          #error_explanation
            %h2
              = pluralize(@dream.errors.count, "error")
              prohibited this dream from being saved:
            %ul
              - @dream.errors.full_messages.each do |msg|
                %li= msg
        .field
          %label{:for => "dream_message"} Reject message
          %br/
          = f.text_area :message, :size => "100%x10", :class => "fullwidth"
        .actions
          = f.submit "Reject Dream", class: "btn"

app/views/admin/index.haml
.span12
  %h3
    %span Admin Dashboard
  %h3 Dreams
  .meta
    %i.icon-signal
    Statistics:
    \#{pluralize(@states[:published], "total published dreams")},
    \#{link_to pluralize(@states[:featured], "featured dream"), dreams_admin_index_path + '?state=4'},
    \#{link_to pluralize(@states[:standard], "standard dream"), dreams_admin_index_path + '?state=3'},
    \#{link_to pluralize(@states[:rejected], "rejected dream"), dreams_admin_index_path + '?state=2'},
    \#{link_to pluralize(@states[:submitted], "submitted dream"), dreams_admin_index_path + '?state=1'},
    \#{link_to pluralize(@states[:pvt], "private dream"), dreams_admin_index_path + '?state=0'}
    %br/
    - if @state == 1
      %b
        There are #{link_to pluralize(@states[:submitted], "submitted dream") , dreams_admin_index_path + '?state=1'} waiting for approval!
  %br
    %h3 Users
    .meta
      %i.icon-signal
      Statistics:
      \#{pluralize(@num_users, "user")} total,
      \#{pluralize(@num_users_active30days, "user")} have been signed-in within the last 30 days.
      %br/
      .meta
        %i.icon-user
        New users:
        \#{pluralize(@num_users_created30days, "user")} have been created within the last 30 days.