config/routes.rb
Lucidly::Application.routes.draw do
  devise_for :users

  resources :admin, :only => [:index] do
    member do
      get 'editreject'
      put 'reject'
      put 'accept'
    end
    collection do
      get 'dreams'
    end
  end

  resources :dreams do
    collection do
      get 'about'
      get 'all'
      get 'mydreams'
    end
    member do
      put 'submit'
    end
    member { post :vote }
    resources :comments, :only => [:create, :destroy]
  end

  get 'tags/:tag', to: 'dreams#index', as: :tag
  root :to => "dreams#index"

end

app/views/layouts/_footer.html.haml
%footer
  .container
    .row
      .span12
        %p
          %a{:href => "http://creativecommons.org/licenses/by-nc-sa/3.0/", :rel => "license"}
            lucidly #{Time.now.year} - Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.
    .clearfix

app/views/layouts/_header.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      %nav
        %ul.nav.pull-left
          %li
            %h1= link_to "Lucidly", '/', id: "logo"
            %li
              %br
        %ul.nav.pull-right
          = request.path == root_path ? raw("<li class='active'>") : raw("<li>")
          = link_to "Featured Dreams", root_path
          = request.path == all_dreams_path ? raw("<li class='active'>") : raw("<li>")
          = link_to "All Dreams", all_dreams_path
          - if user_signed_in?
            = request.path == mydreams_dreams_path ? raw("<li class='active'>") : raw("<li>")
            = link_to "My Dreams", mydreams_dreams_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %i.icon-user
                = current_user.email
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", edit_user_registration_path
                %li= link_to "Sign out", destroy_user_session_path, method: "delete"
          - else
            = request.path == about_dreams_path ? raw("<li class='active'>") : raw("<li>")
            = link_to "About", about_dreams_path
            = request.path == new_user_registration_path ? raw("<li class='active'>") : raw("<li>")
            = link_to "Sign up", new_user_registration_path
            = request.path == new_user_session_path ? raw("<li class='active'>") : raw("<li>")
            = link_to "Sign in", new_user_session_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.haml
!!!
%html
  %head
    %title Lucidly
    = stylesheet_link_tag "application", media: "all"
    = growlyflash_static_notices
    = javascript_include_tag "application"
    = csrf_meta_tag
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .content
      .container
        .row
          = yield
  = render 'layouts/footer'